name: Deploy NextJS

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4

      - name: 'Login to GitHub Container Registry'
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{github.actor}}
          password: ${{secrets.GITHUB_TOKEN}}

      - name: lowercase repository name
        run: |
          echo "GITHUB_REPO_LOWER=${GITHUB_REPOSITORY@L}" >> "${GITHUB_ENV}"

      - name: Build development
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ghcr.io/${GITHUB_REPO_LOWER}:development

      - name: Build production
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ghcr.io/${GITHUB_REPO_LOWER}:production