name: Deploy NextJS

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v4

      - name: 'Login to GitHub Container Registry'
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{github.actor}}
          password: ${{secrets.GITHUB_TOKEN}}

      - name: 'Build production'
        run: |
              docker build . --target production --tag ghcr.io/KanTheAstronaut/nextjs-example:production
              docker push ghcr.io/KanTheAstronaut/nextjs-example:production

      - name: 'Build development'
        run: |
            docker build . --target development --tag ghcr.io/KanTheAstronaut/nextjs-example:development
            docker push ghcr.io/KanTheAstronaut/nextjs-example:development
